backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
  repo: PTA-website-v2

media_folder: "/pta/public/upload" # Folder where user uploaded files should go
public_folder: "/upload"

collections: # A list of collections the CMS should be able to edit
  - name: "SoTeam" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "SLT" # Used in the UI, e.g., "New Post"
    folder: "pta/content/slt" # The path to the folder where the documents are stored
    slug: "{{name}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          tagname: "a",
          required: true,
        }
  - name: "ContactUs" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Board Members" # Used in the UI, e.g., "New Post"
    folder: "pta/content/staff" # The path to the folder where the documents are stored
    slug: "{{name}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }
      - {
          label: "Name",
          name: "name",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Role",
          name: "roles",
          widget: "string",
          tagname: "h4",
          required: true,
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          tagname: "a",
          required: true,
        }
  - name: "Events" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Event" # Used in the UI, e.g., "New Post"
    slug: "{{year}}"
    folder: "pta/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
          pattern:
            [
              "^.{5,30}$",
              "Must have more than 5 characters and less than 30 characters",
            ],
        }
      - { label: "Month (MM)", name: "month", widget: "string", required: true }
      - { label: "Date (DD)", name: "date", widget: "string", required: true }
      - { label: "Year (YYYY)", name: "year", widget: "number", required: true }
      - { label: "Time", name: "time", widget: "string", required: false }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
          pattern:
            [
              "^.{10,500}$",
              "Must have more than 10 characters and less than 500 characters",
            ],
        }
      - {
          label: "Event Sign Up Link",
          name: "signup",
          widget: "string",
          required: true,
        }
      - {
          label: "Event Donate Link",
          name: "donate",
          widget: "string",
          required: true,
        }
  - name: "Minutes" # Used in routes, e.g., /admin/collections/:slug/edit
    create: true # Allow users to create new documents in this collection
    label: "Meeting Minutes Links" # Used in the UI, e.g., "New Post"
    slug: "{{year}}-{{month}}"
    folder: "pta/content/minutes" # The path to the folder where the documents are stored
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "link", name: "link", widget: "string", required: true }
  - name: "Recordings" # Used in routes, e.g., /admin/collections/:slug/edit
    create: true # Allow users to create new documents in this collection
    label: "Meeting Recordings Links" # Used in the UI, e.g., "New Post"
    slug: "{{year}}-{{month}}"
    folder: "pta/content/recordings" # The path to the folder where the documents are stored
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "link", name: "link", widget: "string", required: true }
  - name: "Gallery" # Used in routes, e.g., /admin/collections/:slug/edit
    preview_path: "/upload/{{filename}}" #idk why this doesn't work </3, supposed to upload the images as "/upload {{filename}}" i put it in the thing
    label: "Gallery Images" # Used in the UI, e.g., "New Post"
    folder: "pta/content/gallery" # The path to the folder where the documents are stored
    slug: "{{title}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          preview_path: "/upload/{{filename}}",
        }